version: '3.8'

networks:
  chat-app:
    driver: bridge

services:
  nestjs:
    container_name: nestjs_app_dev
    build:
      context: ./workspaces/nestjs-app/
      dockerfile: ./Dockerfile
    environment:
      - PORT=5555
    ports:
      - "5555:5555"
    networks:
      - chat-app
    volumes:
      - "./workspaces/nestjs-app:/usr/src/app"
      - "/usr/src/app/node_modules"
    command: npm run start:dev

  reactapp:
    container_name: react_app_dev
    environment:
      - PORT=3333
    build:
      context: ./workspaces/react-app
      dockerfile: ./Dockerfile
    ports:
      - "3333:3333"
    networks:
      - chat-app
    volumes:
      - "./workspaces/react-app:/usr/src/app"
      - "/usr/src/app/node_modules"
    command: npm run start
